const cartActionTypes = {
  TOGGLE_HIDDEN_CART: 'TOGGLE_HIDDEN_CART',
  ADD_ITEMS: 'ADD_ITEMS',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART'
};

export default cartActionTypes;
